name: Android CI

on: 
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v2
        - name: set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: gradle
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build with Gradle
          env:
            artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
            artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          run: ./gradlew build              
        - name: Build debug APK
          env:
            artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
            artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          run: bash ./gradlew assembleDebug --stacktrace
        - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: app
            path: automotive/build/outputs/apk/debug/app-debug.apk
